sudo: false
language: node_js
node_js:
  - "5"
  - "6"

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - npm install -g firebase-tools

script:
  - yarn build

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}
